WebtrackFeatures/Models/Default/DefaultViewModel.cs
using System.Collections.Generic;
using WebtrackFeatures.Core.DataItems;

namespace WebtrackFeatures.Models.Default
{
	public class DefaultViewModel
	{
		public Count UserCount { get; set; }
		public Count CustomerCount { get; set; }
		public Count DeviceCount { get; set; }

		public Dictionary<string, int> BrowserCount { get; set; }
		public Dictionary<string, int> OsCount { get; set; }
		public Dictionary<string, int> LanguageCount { get; set; }
		public Dictionary<string, int> LoadTimesDataPoints { get; set; }
		public Dictionary<string, int> DeviceTypeCount { get; set; }


		public Dictionary<string, double> LoadTimes { get; set; }

		public Dictionary<string, int> UserAgents { get; set; }

		public int Visits { get; set; }

	}
}

WebtrackFeatures/Models/Functions/FunctionsData.cs
using System.Collections.Generic;

namespace WebtrackFeatures.Models.Functions
{
	public class FunctionsData
	{
		public Dictionary<string, int> FunctionsCount { get; set; }
	}
}

WebtrackFeatures/Controllers/DefaultController.cs
using MessagePack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using r2pCore.Common.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using WebtrackFeatures.Core;
using WebtrackFeatures.Core.DataItems;
using WebtrackFeatures.Models.Default;

namespace WebtrackFeatures.Controllers
{
	public class DefaultController : Controller
	{
		IMemoryCache _cache;
		public DefaultController(IMemoryCache cache)
		{
			_cache = cache;
		}
		public IActionResult Index()
		{

			var data = new DefaultViewModel
			{
				UserCount = UserFactory.GetUserCount(),
				CustomerCount = CustomerFactory.GetCustomersCount(),
				DeviceCount = DevciceFactory.GetDeviceCount(),
				Visits = CalcVisits(),
				OsCount = new Dictionary<string, int>(),
				LanguageCount = new Dictionary<string, int>(),
				LoadTimes = new Dictionary<string, double>(),
				LoadTimesDataPoints = new Dictionary<string, int>(),
				BrowserCount = new Dictionary<string, int>(),
				DeviceTypeCount = new Dictionary<string, int>(),
				UserAgents = new Dictionary<string, int>()
			};

			foreach (var entry in StatsFactory.GetActivityLogs(_cache))
			{
				if (entry.MessagePackData == null)
					continue;
				if (entry.Action != Actions.PageLoad)
					continue;

				var item = MessagePackSerializer.Deserialize<ActivityLogPackData>(entry.MessagePackData);

				data.LanguageCount.TryGetValue(ToLanguage(item.BrowserInfo.Language), out int lValue);
				data.LanguageCount.AddOrUpdate(ToLanguage(item.BrowserInfo.Language), lValue + 1);
				data.UserAgents.TryGetValue(item.BrowserInfo.UserAgent, out int uaValue);
				data.UserAgents.AddOrUpdate(item.BrowserInfo.UserAgent, uaValue + 1);
			}
			var loadTimes = CalcLoadTimes();
			data.LoadTimes = loadTimes.Times;
			data.LoadTimesDataPoints = loadTimes.DataPoints;


			return View("Index", data);
		}

		int CalcVisits()
		{
			var to = DateTime.Now;
			var from = to.AddDays(-1);
			var data = StatsFactory.GetActivityLogs(from, to);

			return data.Count(c => c.MessagePackData != null && c.Action == Actions.PageLoad && Helpers.IsOnline(c.Url));
		}

		LoadTimes CalcLoadTimes()
		{
			var data = StatsFactory.GetActivityLogs(_cache).ToDictionaryList(c => c.UserId);

			var result = new LoadTimes
			{
				Times = new Dictionary<string, double>(),
				DataPoints = new Dictionary<string, int>()
			};

			var tmpTimes = new Dictionary<string, List<double>>();
			foreach (var key in data.Keys)
			{
				DateTime lastTime = DateTime.Now;
				var lastAction = Actions.PageLoad;
				foreach (var item in data.GetValue(key).OrderBy(x => x.Timestamp))
				{
					var test = false;
					if (Helpers.IsTest(item.Url))
						test = true;
					if (!Helpers.IsWebTrack(item.Url))
						continue;
					if (item.Action != Actions.PageLoad && item.Action != Actions.PageLeave)
						continue;

					var url = item.Url.Split("?")[0];
					url = url.Split("#")[0];
					url = url.Substring(url.LastIndexOf('/'));
					if (Helpers.IsOnline(item.Url))
						url = "/online";
					if (Helpers.IsTest(item.Url))
						url = "test " + url;

					if (item.Action == lastAction)
						continue;

					if (lastAction == Actions.PageLeave)
					{
						if (!tmpTimes.ContainsKey(url))
							tmpTimes.Add(url, new List<double>());

						var dif = item.Timestamp - lastTime;
						var difMS = dif.TotalMilliseconds;
						if (difMS <= 5000)
							tmpTimes[url].Add(difMS);
					}

					lastAction = item.Action;
					lastTime = item.Timestamp;
				}
			}

			foreach (var key in tmpTimes.Keys)
			{

				var count = tmpTimes[key].Count;
				var sum = 0D;

				tmpTimes[key].ForEach(c => sum += c);
				if (count > 0)
				{

					result.DataPoints.Add(key, count);
					result.Times.Add(key, Math.Floor(sum / count));
				}
			}



			return result;
		}

		string ToLanguage(string code)
		{
			return (code.Split('-')[0]) switch
			{
				"da" => "Danish",
				"nn" => "Norwigian",
				"no" => "Norwigian",
				"nb" => "Norwigian",
				"en" => "English",
				"pt" => "Portuguese",
				"de" => "German",
				"sv" => "Swedish",
				"es" => "Spanish",
				"vi" => "Vietnamese",
				"nl" => "Dutch",
				"pl" => "Polish",
				"cs" => "Czech",
				"tr" => "Turkish",
				"it" => "Italian",
				"fr" => "French",
				"fo" => "Faroese",
				"lt" => "Lithuanian",
				"am" => "Amharic",
				"ro" => "Romanian",
				_ => "unknown (" + code + ")",
			};
		}
	}
	public class LoadTimes
	{
		public Dictionary<string, double> Times { get; set; }
		public Dictionary<string, int> DataPoints { get; set; }
	}
}

WebtrackFeatures/Controllers/FunctionsController.cs
using MessagePack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using WebtrackFeatures.Core;
using WebtrackFeatures.Core.DataItems;
using WebtrackFeatures.Models.Functions;
using r2pCore.Common.Extensions;

namespace WebtrackFeatures.Controllers
{
	public class FunctionsController : Controller
	{

		IMemoryCache _cache;
		public FunctionsController(IMemoryCache cache)
		{
			_cache = cache;
		}

		public IActionResult Index()
		{
			var data = new FunctionsData { };

			return View(data);
		}

		public JsonResult Heatmap(string id)
		{
			var logs = StatsFactory.GetActivityLogs(_cache);
			var clicks = new List<Position>();

			foreach (var entry in logs)
			{
				if (entry.MessagePackData == null)
					continue;
				if (!entry.Url.Contains(id))
					continue;
				if (entry.Action != Actions.MouseClick)
					continue;
				try
				{
					var packData = MessagePackSerializer.Deserialize<ActivityLogPackData>(entry.MessagePackData);
					clicks.Add(new Position { X = packData.MousePosition.X, Y = packData.MousePosition.Y, Height = packData.WindowSize.Height, Width = packData.WindowSize.Width });
				}
				catch { }
			}
			return Json(clicks);
		}

		public JsonResult FunctionCount(string id)
		{
			var logs = StatsFactory.GetActivityLogs(_cache);
			var names = StatsFactory.GetFunctionNames(_cache);

			var functions = new Dictionary<string, int>();
			foreach (var entry in logs)
			{
				if (entry.MessagePackData == null)
					continue;
				if (!entry.Url.Contains(id))
					continue;
				if (entry.Action != Actions.MouseClick)
					continue;
				try
				{
					var packData = MessagePackSerializer.Deserialize<ActivityLogPackData>(entry.MessagePackData);
					var key = names.Find(x => x.Selector == packData.TargetSelect).Name;
					if (!key.HasValue())
						key = packData.TargetSelect;

					if (Helpers.IsTest(entry.Url))
						key = "Test - " + key;

					if (!functions.ContainsKey(key))
						functions.Add(key, 0);
					functions[key] += 1;
				}
				catch { }
			}

			return Json(functions);
		}
	}
}

WebtrackFeatures/Views/Default/Index.cshtml
@using WebtrackFeatures.Models.Default
@using System.Collections.Generic;
@model DefaultViewModel
@{
	ViewData["Title"] = "Overview";
}


<div class="container">
	<div class="row">
		<div class="col-3 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Number of users (Total: @Model.UserCount.Total)
				</div>
				<div class="card-body">
					<canvas id="users-chart" width="200" height="200"></canvas>
				</div>
			</div>
		</div>
		<div class="col-3 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Number of Customers (Total: @Model.CustomerCount.Total)
				</div>
				<div class="card-body">
					<canvas id="customer-chart" width="200" height="200"></canvas>
				</div>
			</div>
		</div>
		<div class="col-3 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Number of devices (Total: @Model.DeviceCount.Total)
				</div>
				<div class="card-body">
					<canvas id="device-chart" width="200" height="200"></canvas>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-2 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Browsers
				</div>
				<div class="card-body">
					<canvas id="browser-chart" width="300" height="300"></canvas>
				</div>
			</div>

		</div>
		<div class="col-2 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Client Types
				</div>
				<div class="card-body">
					<canvas id="client-type-chart" width="300" height="300"></canvas>
				</div>
			</div>

		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					OS
				</div>
				<div class="card-body">
					<canvas id="os-chart" width="300" height="300"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-2 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Languages
				</div>
				<div class="card-body">
					<canvas id="language-chart" width="200" height="200"></canvas>
				</div>
			</div>
		</div>
		<div class="col-2 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Average load times <i>(Exprimentel)</i>
				</div>
				<div class="card-body">
					<canvas id="avgload-chart" width="200" height="200"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-2 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Visits latest 24 hours
				</div>
				<div class="card-body">
					<p class="card-text">There has been @Model.Visits visits within the last 24 hours</p>
				</div>
			</div>
		</div>
		<div class="col-2 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Avrage loadtimes data points
				</div>
				<div class="card-body">
					<canvas id="avgload-datapoints-chart" width="200" height="200"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-body">
					* Data is calculated and can there for only be used to show a estimate statistic over the clients and will not give 100% acurate numbers<br />
					** Data is fron now and a month back, eg. to day is the 15 of January then the data in the calculations will be from the 15 of December to the 15 of January
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		&nbsp;
	</div>
</div>

<script type="text/javascript">
	window["_model"] = @Html.Raw(Json.Serialize(@Model));
</script>

<script src="https://cdn.jsdelivr.net/npm/ua-parser-js@0/dist/ua-parser.min.js"></script>
<script src="./Assets/js/Chart.min.js" type="text/javascript"></script>
<script src="./pages/default/Index.js" type="text/javascript"></script>

WebtrackFeatures/Views/Functions/Index.cshtml
@using WebtrackFeatures.Models.Functions
@model FunctionsData
@{
	ViewData["Title"] = "Functions";
}

<div class="container">
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Functions used on web-track
				</div>
				<div class="card-body">
					A list of functions used on webtrack, the lists are calculated from witch buttons have been used the last month.
					For general information go to the @Html.ActionLink("Overview", "Index", "Default", new { area = "" }, new { @class = "text-black" }) page and for witch reports is used goto the @Html.ActionLink("Reports", "Index", "Reports", new { area = "" }, new { @class = "text-black" }) page
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Online
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="online-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="online-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="online_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					History
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="history-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="history-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="history_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Reports
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="reports-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="reports-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="reports_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Alerts
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="alerts-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="alerts-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="alerts_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					POI
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="poi-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="poi-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="poi_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Messages
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="messages-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="messages-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="messages_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-1 col-sm">
			<div class="card shadow-sm rounded">
				<div class="card-header">
					Tachodownload
					<button type="button" class="btn btn-info float-right btn-sm btn-functions" id="tachodownload-functions" style="margin-left:10px">Show functions</button>&nbsp;
					<button type="button" class="btn btn-info float-right btn-sm" id="tachodownload-download">Download as PNG</button>
				</div>
				<div class="card-body" height="800">
					<canvas id="tachodownload_heatmap"></canvas>
				</div>
			</div>
		</div>
	</div>
</div>


<div id="popContainer" class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header ">
				<h5 class="modal-title">Functions <span is="popName">nopage</span></h5>
				<button type="button" class="close" data-dismiss="modal" id="popClose" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body" style="max-height:600px; overflow:auto;">
				<a href="#" class="badge badge-pill badge-dark" id="popDownload">Download as XLS</a>
				<hr />
				<table id="popTable" class="table"></table>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
	window["_model"] = @Html.Raw(Json.Serialize(@Model));
</script>
<script src="./Assets/js/heatmap.js" type="text/javascript"></script>
<script src="./pages/functions/Index.js" type="text/javascript"></script>

WebtrackFeatures/Views/Shared/_Layout.cshtml
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<style type="text/css">
		.row {
			margin-top: 1rem;
		}
	</style>
	<title>
		Webtrack Stats Collection - @ViewData["Title"]
	</title>
</head>
<body>
	<div class="navbar navbar-fixed-top bg-primary">
		<div class="container">
			<div class="navbar-header">
				<h2 class="text-white">
					Webtrack Stats Collection - @ViewData["Title"]
				</h2>
			</div>
			<div class="navbar">
				<ul class="nav navbar-nav">
					<li class="nav-item">@Html.ActionLink("Overview", "Index", "Default", new { area = "" }, new { @class = "text-white" })</li>
					<li class="nav-item">@Html.ActionLink("Functions", "Index", "Functions", new { area = "" }, new { @class = "text-white" })</li>
					<li class="nav-item">@Html.ActionLink("Reports", "Index", "Reports", new { area = "" }, new { @class = "text-white" })</li>
				</ul>
			</div>
		</div>
	</div>

	<script type="text/javascript" src="./assets/js/newDom.js"></script>
	<script type="text/javascript" src="./assets/js/Helpers.js"></script>
	<div class="container body-content">
		@RenderBody()
	</div>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>